name: Testing

on: [push]

jobs:
  testing:

    runs-on: ubuntu-latest
    timeout-minutes: 10 
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencie
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Install dev dependencies
        run: |
          pip install -r requirements_dev.txt
      - name: Run linting
        run: |
          python -m flake8
      - name: Run test case
        run: |
          python run_basic_heuristics.py